----------------------
 jEAC BUILD PROCEDURE
----------------------

NOTES:
 - According to this page (http://java.sun.com/j2se/embedded/index.jsp), embedding the JRE costs money.



WINDOWS XP:

 1. Export JAR:
	- Run FATJAR, export to: BUILD/staging/jEAC.jar
 2. Build EXE:
	- Run launch4j, load: jEAC-launch4j-nixon.xml
	- Build jEAC, export to: BUILD/staging/jEAC.exe
 3. Create ZIP FILE:
 	- Create new zip file: BUILD/staging/staging.zip
 	- Uncheck "include system and hidden files" (to omit .svn directories)
	- Include: lib-win32/, examples/, jEAC.exe
 4. Create RELEASE:
	- In Eclipse, create: BUILD/releases/X.Y.Z
	- Rename staging.zip to: BUILD/releases/X.Y.Z/jEAC-X.Y.Z-win32.zip
 5. PUBLISH:
	- ...
	


MAX OSX:

 1. Create ZIP FILE:
 	- Create new zip file: BUILD/staging/staging.zip
 	- Uncheck "include system and hidden files" (to omit .svn directories)
	- Include: lib-OSX/, examples/, jEAC.jar (created earlier)
 2. Create RELEASE:
	- Rename staging.zip to: BUILD/releases/X.Y.Z/jEAC-X.Y.Z-win32.zip
 3. PUBLISH:
 	- ...



LINUX:

 1. ...



GENERIC:

 1. ...
